version: '3.4'

networks:
  default:
    driver: bridge

services:
  nginx:
    build:
      context: proxy
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./front/dist/:/etc/nginx/html/dist/
      - ./proxy/data/nginx_app/:/etc/nginx/conf.d
    networks:
      - default
  api:
    build:
      context: backend
      dockerfile: Dockerfile
    command: flask run --host=0.0.0.0
    ports:
      - "5000:5000"
    env_file:
      - .envs/.local/.env.flaskenv
    volumes:
      - ./backend/src:/code/src
      - ./backend/tests:/code/tests
      - ./backend/jdd/xml_cisu:/jdd/xml_cisu
    networks:
      - default