version: '3.4'

networks:
  default:
    driver: bridge
  enki_default:
    external: true


volumes:
  kong-datastore:

services:
  kong-db:
    image: postgres
    volumes:
      - kong-datastore:/var/lib/postgresql/data
    networks:
      - default
      - enki_default
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB:       api-gw
      POSTGRES_USER:     kong
      POSTGRES_PASSWORD: kong

  kong:
    build:
      context: gateway
      dockerfile: Dockerfile
    depends_on:
      - kong-db
    networks:
      - default
      - enki_default
    ports:
      - "8000:8000" # Listener
      - "8001:8001" # Admin API
    environment:
      KONG_DATABASE:         postgres
      KONG_PG_HOST:          kong-db
      KONG_PG_PORT:          5432
      KONG_PG_USER:          kong
      KONG_PG_PASSWORD:      kong
      KONG_PG_DATABASE:      api-gw
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG:  /dev/stderr
      KONG_ADMIN_ERROR_LOG:  /dev/stderr
      KONG_PROXY_LISTEN:     0.0.0.0:8000, 0.0.0.0:8443 ssl
      KONG_ADMIN_LISTEN:     0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_PLUGINS:          "oidc,bundled"
      KONG_LOG_LEVEL:        debug

