version: '2'

networks:
  default:
    driver: bridge
  enki_default:
    external: true

services:
  nginx:
    build:
      context: proxy
      dockerfile: Dockerfile
    ports:
      - "443:443"
      - "8000:8000"
      - "9000:9000"
    volumes:
      - ./front/dist/:/etc/nginx/html/dist/
      - ./proxy/data/nginx/:/etc/nginx/conf.d
      -  /etc/letsencrypt/:/etc/letsencrypt
    networks:
      - default
      - enki_default
