version: '3.4'

networks:
  default:
    driver: bridge

services:
  nginx:
    build:
      context: proxy
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - ./proxy/data/nginx_gateway/:/etc/nginx/conf.d
    networks:
      - default
  kong:
    build:
      context: kong
      dockerfile: Dockerfile
    env_file:
      - .envs/.local/.env.kong
    networks:
      - default
    ports:
      - "8000:8000" # Listener
      - "8001:8001" # Admin API
      - "8002:8002" # Admin GUI