# WARNING: this file is not suitable for production, please use with caution
version: '2'


services:
  enki-api:
    build: .
    command: flask run --host=0.0.0.0
    env_file:
      - .envs/.local/.env.flaskenv
      - .envs/.local/.env.pg
      - .envs/.local/.env.minio
    volumes:
      - ./src:/code/src
      - ./tests:/code/tests
      - ./jdd/xml_cisu:/jdd/xml_cisu
    depends_on:
      - postgres
    networks:
      - default
      - enki_default

  postgres:
    image: mdillon/postgis
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .envs/.local/.env.pg
#    volumes:
#      - ./pgdata/dev:/var/lib/postgresql/data
    networks:
      - default

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - default
      - enki_default

  minio:
    image: minio/minio
    volumes:
      - minio-data:/data
    expose:
      - "9000"
    env_file:
      - .envs/.local/.env.minio
    command: server data/
    networks:
      - default
      - enki_default

volumes:
  minio-data:

networks:
  default:
    driver: bridge
  enki_default:
    external: true

