# WARNING: this file is not suitable for production, please use with caution
# This file provides the external ressources (like Postgres) without the application code
version: '3'

services:
  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - "5431:5432"
    env_file:
      - .envs/.test/.env.pg
    volumes:
      - ./pgdata/test:/var/lib/postgresql/data