# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  sapeurs-api:
    image: sapeurs-api
    build: .
    depends_on:
      - pg
    command: flask run --host=0.0.0.0
    env_file:
      - .envs/.local/.env.flaskenv
      - .envs/.local/.env.pg
    environment:
      - CONNECT_TO_SGE: true
    ports:
      - "5000:5000"
    volumes:
      - ./src:/src
      - ./tests:/tests
    networks:
      - sge_default
      - default

  postgres:
    image: postgres
    restart: unless-stopped
    env_file:
      - .envs/.local/.env.pg
    volumes:
      - ./pgdata/dev:/var/lib/postgresql/data
    networks:
      - default

networks:
  sge_default:
    external: true
  default:
    driver: bridge