# WARNING: this file is not suitable for production, please use with caution
# This file provides the external ressources (like Postgres) without the application code
version: '3'

services:
  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sapeurs-dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg-password
    volumes:
      - ./pgdata:/var/lib/postgresql/data