# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  postgres:
    image: mdillon/postgis
    restart: unless-stopped
    env_file:
      - .envs/.test/.env.pg
    ports:
      - "5433:5432"
    networks:
      - default
#
#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
#    restart: unless-stopped
#    env_file:
#      - .envs/.test/.env.elastic
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    ports:
#      - 9201:9200

networks:
  default:
    driver: bridge
