version: '3'

services:
  keycloak-provision:
    build:
      context: ./docker
      dockerfile: Dockerfile.provision
    env_file:
      - .env
    networks:
      - default
      - enki_default

networks:
  default:
    driver: bridge
  enki_default:
    external: true