version: '3'

services:
  postgres:
      image: postgres
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password

  keycloak:
      image: keycloak
      build: .
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
      volumes:
        - ./realms/sapeurs.json:/tmp/quarkus-realm.json
        - ./enki-theme/:/opt/jboss/keycloak/themes/enki-theme

  keycloak-fwd:
    image: marcnuri/port-forward
    environment:
      REMOTE_HOST: keycloak
      REMOTE_PORT: 8080
      LOCAL_PORT: 8084
    ports:
      - 8084:8084
    networks:
        - default

networks:
  default:
    driver: bridge
  backend_default:
    external: true