version: '3'

services:
  keycloak-db:
      image: postgres
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password

  keycloak:
      build: .
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: keycloak-db
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
        KEYCLOAK_IMPORT: /tmp/enki-realm-export.json
      ports:
        - 8080:8080
      volumes:
        - ./realms/enki-realm-export.json:/tmp/enki-realm-export.json
        - ./enki-theme/:/opt/jboss/keycloak/themes/enki-theme
      networks:
        - default
        - enki_default

  keycloak-fwd:
    image: marcnuri/port-forward
    environment:
      REMOTE_HOST: keycloak
      REMOTE_PORT: 8080
      LOCAL_PORT: 8084
    ports:
      - 8084:8084
    networks:
      - default
      - enki_default

networks:
  default:
    driver: bridge
  enki_default:
    external: true