version: '3'

services:
  keycloak:
      image: keycloak
      build: .
      environment:
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
      volumes:
        - ./realms/sapeurs.json:/tmp/quarkus-realm.json
        - ./enki-theme/:/opt/jboss/keycloak/themes/enki-theme
      ports:
        - 8080:8080
