version: '2'

services:
  front:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: npx serve
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src
      - ./dist:/app/dist
      - ./design-system:/app/design-system
    networks:
      - default
      - enki_default

networks:
  default:
    driver: bridge
  enki_default:
    external: true

