version: '3.5'

services:
  front:
    build: .
    ports:
      - "1337:1337"
    volumes:
      - ./src:/app/src
    networks:
      - default
      - enki_default

networks:
  default:
    driver: bridge
  enki_default:
    external: true
