version: '3.4'

networks:
  default:
    driver: bridge
  enki_default:
    external: true

services:
  kong-provision:
    build:
      context: ./docker
      dockerfile: Dockerfile.provision
    env_file:
      - .env
    networks:
      - default
      - enki_default
