# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  api:
    image: sapeur_api
    build: .
    command: gunicorn -b 0.0.0.0:5000 sapeur_api.wsgi:app
    env_file:
      - ./.envs/.local/.flaskenv
      - ./.envs/.local/.pg_env
    volumes:
      - ./sapeur_api:/code/sapeur_api
    ports:
      - "5000:5000"

  postgres:
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - ./.envs/.local/.pg_env
    volumes:
      - ./scripts/init_users.sh:/docker-entrypoint-initdb.d/init_users.sh

#  rabbitmq:
#    image: rabbitmq
#  redis:
#    image: redis
#  celery:
#    image: sapeur_api
#    command: "celery worker -A sapeur_api.celery_app:app"
#    env_file:
#      - ./.envs/.local/.flaskenv
#    volumes:
#      - .:/code
#    depends_on:
#      - rabbitmq

volumes:
  pg-data:
    driver: local