version: '3'

services:
  keycloak-db:
    image: postgres
    env_file:
      - .env
    networks:
      - default

  keycloak:
    build: .
    env_file:
      - .env
    volumes:
      - ./realms/enki-realm-export.json:/tmp/enki-realm-export.json
      - ./enki-theme/:/opt/jboss/keycloak/themes/enki-theme
      # surcharge de config pour que le theme n'ait pas de cache et qu'on puisse bosser dessus
      - ./standalone-ha.xml:/opt/jboss/keycloak/standalone/configuration/standalone-ha.xml
    networks:
      - default
      - enki_default

  keycloak-fwd:
    image: marcnuri/port-forward
    environment:
      REMOTE_HOST: keycloak
      REMOTE_PORT: 8080
      LOCAL_PORT: 8084
    ports:
      - 8084:8084

networks:
  default:
    driver: bridge
  enki_default:
    external: true