version: '2'

services:
  keycloak-db:
    image: postgres
    env_file:
      - .env
    networks:
      - default

  keycloak:
    build: .
    env_file:
      - .env
    volumes:
      - ./enki-theme/:/opt/jboss/keycloak/themes/enki-theme
    networks:
      - default
      - enki_default
networks:
  default:
    driver: bridge
  enki_default:
    external: true
