version: '2'

services:
  keycloak-db:
    image: postgres
    env_file:
      - .env
    networks:
      - default

  keycloak:
    build: .
    env_file:
      - .env
    volumes:
      - ./realms/enki-realm-export-prod.json:/tmp/enki-realm-export-prod.json
      - ./enki-theme/:/opt/jboss/keycloak/themes/enki-theme
      # surcharge de config pour que le theme n'ait pas de cache et qu'on puisse bosser dessus
      - ./standalone-ha.xml:/opt/jboss/keycloak/standalone/configuration/standalone-ha.xml
      - /etc/letsencrypt/live/enki-crise.fr/fullchain.pem:/etc/x509/https/tls.crt
      - /etc/letsencrypt/live/enki-crise.fr/privkey.pem:/etc/x509/https/tls.key
    networks:
      - default
      - enki_default
networks:
  default:
    driver: bridge
  enki_default:
    external: true
