version: '3'

services:
  keycloak-db:
    image: postgres
    env_file:
      - .env
    networks:
      - default

  keycloak:
    build: .
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - ./realms/enki-realm-export.json:/tmp/enki-realm-export.json
      - ./enki-theme/:/opt/jboss/keycloak/themes/enki-theme
    networks:
      - default
      - enki_default

networks:
  default:
    driver: bridge
  enki_default:
    external: true